#!/usr/bin/env python3
"""Export SpaceShift SQLite state into a Postgres migration bundle."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sqlite3
import time
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SQLITE_MASTER_SQL = """
SELECT type, name, tbl_name, sql
FROM sqlite_master
WHERE sql IS NOT NULL
  AND type IN ('table', 'index')
  AND name NOT LIKE 'sqlite_%'
ORDER BY
  CASE type
    WHEN 'table' THEN 0
    WHEN 'index' THEN 1
    ELSE 2
  END,
  name;
""".strip()


@dataclass(frozen=True)
class TableExport:
    name: str
    columns: list[str]
    dependencies: list[str]
    row_count: int


def resolve_default_state_db() -> Path:
    server_dir = Path(__file__).resolve().parent
    project_root = server_dir.parents[1]
    return project_root / "Data" / "state" / "spaceshift_state.sqlite3"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export SQLite state and emit Postgres migration artifacts."
    )
    parser.add_argument(
        "--sqlite-db",
        type=Path,
        default=resolve_default_state_db(),
        help="Path to the SQLite state database.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("SpaceShiftGame/Reports/postgres_migration_bundle"),
        help="Output bundle directory.",
    )
    parser.add_argument(
        "--include-empty-tables",
        action="store_true",
        help="Write CSV files even when a table has zero rows.",
    )
    return parser.parse_args()


def sqlite_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sqlite_value_to_csv(value: Any) -> Any:
    if value is None:
        return r"\N"
    if isinstance(value, bytes):
        return "\\x" + value.hex()
    return value


def list_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    return [str(row["name"]) for row in rows if isinstance(row["name"], str)]


def list_columns(conn: sqlite3.Connection, table_name: str) -> list[str]:
    rows = conn.execute(f"PRAGMA table_info({sqlite_ident(table_name)})").fetchall()
    return [str(row["name"]) for row in rows if isinstance(row["name"], str)]


def list_dependencies(conn: sqlite3.Connection, table_name: str, known: set[str]) -> list[str]:
    rows = conn.execute(
        f"PRAGMA foreign_key_list({sqlite_ident(table_name)})"
    ).fetchall()
    dependencies: set[str] = set()
    for row in rows:
        dependency = row["table"]
        if isinstance(dependency, str) and dependency in known and dependency != table_name:
            dependencies.add(dependency)
    return sorted(dependencies)


def sort_tables_by_dependency(dependency_map: dict[str, set[str]]) -> list[str]:
    indegree = {name: len(dependencies) for name, dependencies in dependency_map.items()}
    children: dict[str, set[str]] = defaultdict(set)
    for table_name, dependencies in dependency_map.items():
        for dependency in dependencies:
            children[dependency].add(table_name)

    queue = deque(sorted(name for name, degree in indegree.items() if degree == 0))
    ordered: list[str] = []
    while queue:
        current = queue.popleft()
        ordered.append(current)
        for child in sorted(children.get(current, set())):
            indegree[child] -= 1
            if indegree[child] == 0:
                queue.append(child)

    if len(ordered) != len(indegree):
        remaining = sorted(name for name in indegree if name not in set(ordered))
        ordered.extend(remaining)
    return ordered


def render_sqlite_schema(statements: list[str]) -> str:
    lines = [
        "-- Generated from sqlite_master",
        f"-- generated_utc={time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}",
        "",
    ]
    lines.extend(statements)
    lines.append("")
    return "\n".join(lines)


def convert_statement_to_postgres(statement: str) -> str:
    converted = statement
    converted = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        converted,
        flags=re.IGNORECASE,
    )
    converted = re.sub(r"\bAUTOINCREMENT\b", "", converted, flags=re.IGNORECASE)
    converted = re.sub(r"\bREAL\b", "DOUBLE PRECISION", converted, flags=re.IGNORECASE)
    converted = re.sub(r"\bBLOB\b", "BYTEA", converted, flags=re.IGNORECASE)
    converted = re.sub(r"\s+", " ", converted).strip()
    if not converted.endswith(";"):
        converted += ";"
    return converted


def render_postgres_schema(statements: list[str]) -> str:
    lines = [
        "-- Generated by sqlite_to_postgres_bundle.py",
        "-- Review before production use.",
        f"-- generated_utc={time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}",
        "",
        "BEGIN;",
    ]
    lines.extend(convert_statement_to_postgres(statement) for statement in statements)
    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def export_table_csv(
    conn: sqlite3.Connection,
    table_name: str,
    columns: list[str],
    output_path: Path,
) -> int:
    select_columns = ", ".join(sqlite_ident(column) for column in columns)
    query = f"SELECT {select_columns} FROM {sqlite_ident(table_name)}"
    row_count = 0
    with output_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(columns)
        for row in conn.execute(query):
            values = [sqlite_value_to_csv(row[column]) for column in columns]
            writer.writerow(values)
            row_count += 1
    return row_count


def render_psql_loader(
    table_exports: list[TableExport],
    ordered_tables: list[str],
    data_dir_name: str,
    include_empty_tables: bool,
) -> str:
    by_name = {table.name: table for table in table_exports}
    lines = [
        "-- Generated by sqlite_to_postgres_bundle.py",
        "-- Run from this bundle directory: psql \"$POSTGRES_DSN\" -f load_postgres.sql",
        "",
        r"\set ON_ERROR_STOP on",
        r"\echo Applying schema_postgres.sql",
        r"\i schema_postgres.sql",
        "",
        "BEGIN;",
    ]
    for table_name in ordered_tables:
        table = by_name.get(table_name)
        if table is None:
            continue
        if table.row_count == 0 and not include_empty_tables:
            continue
        columns_sql = ", ".join(pg_ident(column) for column in table.columns)
        copy_path = f"./{data_dir_name}/{table.name}.csv"
        lines.append(
            rf"\copy {pg_ident(table.name)} ({columns_sql}) FROM {pg_literal(copy_path)} "
            r"WITH (FORMAT csv, HEADER true, NULL '\N');"
        )
    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    sqlite_db = args.sqlite_db.resolve()
    output_dir = args.output_dir.resolve()
    data_dir = output_dir / "data"

    if not sqlite_db.exists():
        print(f"SQLite DB not found: {sqlite_db}")
        print("Run mock_server.py or smoke_test.py first to bootstrap schema/state.")
        return 2

    output_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(sqlite_db)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        tables = list_tables(conn)
        known_tables = set(tables)
        dependency_map: dict[str, set[str]] = {}
        table_exports: list[TableExport] = []

        for table_name in tables:
            columns = list_columns(conn, table_name)
            dependencies = list_dependencies(conn, table_name, known_tables)
            row_count = export_table_csv(
                conn=conn,
                table_name=table_name,
                columns=columns,
                output_path=data_dir / f"{table_name}.csv",
            )
            table_exports.append(
                TableExport(
                    name=table_name,
                    columns=columns,
                    dependencies=dependencies,
                    row_count=row_count,
                )
            )
            if row_count == 0 and not args.include_empty_tables:
                (data_dir / f"{table_name}.csv").unlink(missing_ok=True)
            dependency_map[table_name] = set(dependencies)

        ordered_tables = sort_tables_by_dependency(dependency_map)

        schema_rows = conn.execute(SQLITE_MASTER_SQL).fetchall()
        schema_statements = []
        for row in schema_rows:
            sql = row["sql"]
            if isinstance(sql, str):
                statement = sql.strip()
                if statement:
                    if not statement.endswith(";"):
                        statement += ";"
                    schema_statements.append(statement)
    finally:
        conn.close()

    manifest = {
        "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "sqlite_db": str(sqlite_db),
        "tables": [
            {
                "name": table.name,
                "row_count": table.row_count,
                "columns": table.columns,
                "dependencies": table.dependencies,
            }
            for table in table_exports
        ],
        "load_order": ordered_tables,
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    (output_dir / "schema_sqlite.sql").write_text(
        render_sqlite_schema(schema_statements),
        encoding="utf-8",
    )
    (output_dir / "schema_postgres.sql").write_text(
        render_postgres_schema(schema_statements),
        encoding="utf-8",
    )
    (output_dir / "load_postgres.sql").write_text(
        render_psql_loader(
            table_exports=table_exports,
            ordered_tables=ordered_tables,
            data_dir_name=data_dir.name,
            include_empty_tables=args.include_empty_tables,
        ),
        encoding="utf-8",
    )

    total_rows = sum(table.row_count for table in table_exports)
    copied_tables = sum(
        1
        for table in table_exports
        if table.row_count > 0 or args.include_empty_tables
    )
    print(f"SQLite source: {sqlite_db}")
    print(f"Bundle output: {output_dir}")
    print(f"Tables discovered: {len(table_exports)}")
    print(f"Tables copied to CSV: {copied_tables}")
    print(f"Rows exported: {total_rows}")
    print("Generated files: manifest.json, schema_sqlite.sql, schema_postgres.sql, load_postgres.sql")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
